### ISSUE TITLE
Complete ComplaintActivity

### ISSUE THREAD

**Issue by krharsh17** [hackslash-nitp/messsy#15]
Follow the TODOs in the file to complete the code. Do not remove the comments, just remove the TODO from the comment line.

**Comment by mdzaidalam52** [comment]
I would like to work on it. Please assign me this task.

**Comment by mdzaidalam52** [comment]
Remove this Issue as this has been sorted.

**Comment by ayushman999** [comment]
Completed by @sameershekhar100
