### ISSUE TITLE
dependencies should be updated

### ISSUE THREAD

**Issue by vipozdn** [hackslash-nitp/messsy#45]
Some dependencies in build.gradle(module: app) and in build.gradle(project level) should be updated

![app_depend](https://user-images.githubusercontent.com/32436953/109490794-c7774700-7a99-11eb-82a2-beb5f6ee94b0.png)
![project_depend](https://user-images.githubusercontent.com/32436953/109490791-c6deb080-7a99-11eb-85bc-b0e4fa1b1589.png)

assign me

**Comment by ayushman999** [comment]
This isn't really an issue right now, so try choosing one from what we have created.
